---
- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - community.general
    - foefesfwe.fweiogwe4gfwo
  tasks:

  - name: Clone this repo using the hg module
    hg:
      dest: target
      repo: https://bitbucket.org/ansibleengineering/test-playbooks-hg
