namespace: alancoding
name: deps
version: 1.0.2
readme: README.md
authors:
- Alan Rominger <arominge@redhat.com>
description: demo collection with just a handful of dependencies
license:
- GPL-2.0-or-later
tags: []

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies:
  alancoding.basic: 0.0.5
  awx.awx: ">=8.0.0"
  devoperate.base: 0.1.0
  crivetimihai.workstation: 1.0.12
  dynatrace_innovationlab.collection: 1.0.0
  ganeshrn.test: 1.0.0
  debops.debops: 1.1.4
  cjsteel.development_environment: 1.2.1
  xlab_si.sesame: 1.0.0
  # inverse_inc.packetfence: 0.2.0  # could not find
  # stopped at id 12 https://galaxy.ansible.com/api/v2/collections/

repository: https://github.com/AlanCoding/collection-dependencies-demo/tree/master/deps
documentation: https://github.com/AlanCoding/collection-dependencies-demo/tree/master/deps/README.md
homepage: https://github.com/AlanCoding/collection-dependencies-demo
issues: https://github.com/AlanCoding/collection-dependencies-demo/issues

build_ignore:
- target
- LICENSE
- Makefile
- '*.tar.gz'
