namespace: alancoding
name: awx_venv
version: 1.0.0
readme: README.md
authors:
- Alan Rominger <arominge@redhat.com>
description: A collection that contains all dependencies needed to replicate AWX Ansible venv
license:
- GPL-2.0-or-later
license_file: ''
tags: []
dependencies:
  theforeman.foreman: "*"
  google.cloud: "*"
  azure.azcollection: "*"
  ovirt.ovirt_collection: "*"
  # not yet on Galaxy
  ansible.amazon: "*"
  openstack.cloud: "*"
  community.vmware: "*"
repository: https://github.com/AlanCoding/collection-dependencies-demo
documentation: https://github.com/AlanCoding/collection-dependencies-demo
homepage: https://github.com/AlanCoding/collection-dependencies-demo
issues: https://github.com/AlanCoding/collection-dependencies-demo
build_ignore: []
